services:
  xsshunterexpress-db:
    image: postgres:17
    container_name: xsshunterexpress-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
    volumes:
      - ./postgres-db-data:/var/lib/postgresql/data/pgdata
  xsshunterexpress-service:
    image: ssqlone/xsshunter:latest
    container_name: xsshunterexpress-service
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 8080
    volumes:
      - ./payload-fire-images:/app/payload-fire-images
    depends_on:
      xsshunterexpress-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
  xsshunterexpress-trufflehog:
    image: ssqlone/xsshunter-trufflehog:latest
    container_name: xsshunterexpress-trufflehog
    restart: unless-stopped
    expose:
      - 8000
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8000 || exit 1"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
